name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PLAYWRIGHT_BASE_URL: 'https://horizon-ui.com/horizon-ui-chakra/admin/default'
  BROWSER: 'chrome'   #$ {{ secrets.BROWSER }} Make sure to set this secret
  PLAYWRIGHT_TIMEOUT: 60000

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-jammy  # Use the Playwright Docker image
    if: |
      github.event_name == 'pull_request' ||
      github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Install browsers
        run: npx playwright install firefox webkit

      - name: Run Tests
        run: npm run test:chromium
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        id: allure-report
        with:
          allure_results: ./allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages